apiVersion: apps/v1
kind: Deployment
metadata:
  name: suraj-banking-deploy1
  labels:
    app: banking
spec:
  replicas: 3
  selector:
    matchLabels:
      app: banking
  template:
    metadata:
      labels:
        app: banking
    spec:
      containers:
      - name: suraj-javabanking-container
        image: suraj838098/bank-webapp:v1.0
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: suraj-banking-np-service
  labels:
    app: banking
spec:
  selector:
    app: banking

  type: NodePort
  ports:
  - nodePort: 31036
    port: 8081
    targetPort: 8081
